name: Coverage
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Set GOPATH and PATH
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
      - name: Install Dependencies
        run: |
          go get -v -t -d ./...
          go get -v golang.org/x/lint/golint

      - name: Run coverage
        run: |
          export CODECOV_TOKEN=`b2bb77f1-5155-4f2b-90ab-bef6bd3ddeaa`
          go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)